id: I57640195
legacy_id: P007004
ocr_import_info:
  bdrc_scan_id: W23693
  source: bdrc
  ocr_info:
    timestamp: '2020-03-29T18:40:44'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-02T01:58:25.923164+00:00'
last_modified: 2022-09-02 10:10:10.695021
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W23693
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW23693
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: གསུང་འབུམ། མཁས་གྲུབ་རྗེ ༼སྐུ་འབུམ་པར་མ༽
  author: མཁས་གྲུབ་རྗེ་དགེ་ལེགས་དཔལ་བཟང་།
statistics:
  ocr_word_mean_confidence_index: 0.5605687049413942
  ocr_word_median_confidence_index: 0.5600000023841858
quality: null
bases:
  I0692:
    source_metadata:
      id: http://purl.bdrc.io/resource/I0692
      total_pages: 810
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I0692.txt
    statistics:
      ocr_word_median_confidence_index: 0.5699999928474426
      ocr_word_mean_confidence_index: 0.5601867001136848
    legacy_id: v001
  I0693:
    source_metadata:
      id: http://purl.bdrc.io/resource/I0693
      total_pages: 826
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I0693.txt
    statistics:
      ocr_word_median_confidence_index: 0.6299999952316284
      ocr_word_mean_confidence_index: 0.6024663207259904
    legacy_id: v002
  I0706:
    source_metadata:
      id: http://purl.bdrc.io/resource/I0706
      total_pages: 790
      volume_number: 15
      volume_pages_bdrc_intro: 2
    order: 15
    base_file: I0706.txt
    statistics:
      ocr_word_median_confidence_index: 0.5400000214576721
      ocr_word_mean_confidence_index: 0.5453097799296963
    legacy_id: v015
  I0704:
    source_metadata:
      id: http://purl.bdrc.io/resource/I0704
      total_pages: 800
      volume_number: 13
      volume_pages_bdrc_intro: 2
    order: 13
    base_file: I0704.txt
    statistics:
      ocr_word_median_confidence_index: 0.550000011920929
      ocr_word_mean_confidence_index: 0.5551090361715226
    legacy_id: v013
  I0705:
    source_metadata:
      id: http://purl.bdrc.io/resource/I0705
      total_pages: 766
      volume_number: 14
      volume_pages_bdrc_intro: 2
    order: 14
    base_file: I0705.txt
    statistics:
      ocr_word_median_confidence_index: 0.5099999904632568
      ocr_word_mean_confidence_index: 0.530067642160535
    legacy_id: v014
  I0694:
    source_metadata:
      id: http://purl.bdrc.io/resource/I0694
      total_pages: 700
      volume_number: 3
      volume_pages_bdrc_intro: 2
    order: 3
    base_file: I0694.txt
    statistics:
      ocr_word_median_confidence_index: 0.6000000238418579
      ocr_word_mean_confidence_index: 0.58705667301379
    legacy_id: v003
  I0698:
    source_metadata:
      id: http://purl.bdrc.io/resource/I0698
      total_pages: 810
      volume_number: 7
      volume_pages_bdrc_intro: 2
    order: 7
    base_file: I0698.txt
    statistics:
      ocr_word_median_confidence_index: 0.5899999737739563
      ocr_word_mean_confidence_index: 0.5761346264405155
    legacy_id: v007
  I0703:
    source_metadata:
      id: http://purl.bdrc.io/resource/I0703
      total_pages: 696
      volume_number: 12
      volume_pages_bdrc_intro: 2
    order: 12
    base_file: I0703.txt
    statistics:
      ocr_word_median_confidence_index: 0.5
      ocr_word_mean_confidence_index: 0.5210035985309616
    legacy_id: v012
  I0701:
    source_metadata:
      id: http://purl.bdrc.io/resource/I0701
      total_pages: 832
      volume_number: 10
      volume_pages_bdrc_intro: 2
    order: 10
    base_file: I0701.txt
    statistics:
      ocr_word_median_confidence_index: 0.6000000238418579
      ocr_word_mean_confidence_index: 0.5815521722101309
    legacy_id: v010
  I0699:
    source_metadata:
      id: http://purl.bdrc.io/resource/I0699
      total_pages: 812
      volume_number: 8
      volume_pages_bdrc_intro: 2
    order: 8
    base_file: I0699.txt
    statistics:
      ocr_word_median_confidence_index: 0.550000011920929
      ocr_word_mean_confidence_index: 0.5507351420188568
    legacy_id: v008
  I0707:
    source_metadata:
      id: http://purl.bdrc.io/resource/I0707
      total_pages: 712
      volume_number: 16
      volume_pages_bdrc_intro: 2
    order: 16
    base_file: I0707.txt
    statistics:
      ocr_word_median_confidence_index: 0.550000011920929
      ocr_word_mean_confidence_index: 0.5522736185067199
    legacy_id: v016
  I0697:
    source_metadata:
      id: http://purl.bdrc.io/resource/I0697
      total_pages: 754
      volume_number: 6
      volume_pages_bdrc_intro: 2
    order: 6
    base_file: I0697.txt
    statistics:
      ocr_word_median_confidence_index: 0.5400000214576721
      ocr_word_mean_confidence_index: 0.5522824054635626
    legacy_id: v006
  I0700:
    source_metadata:
      id: http://purl.bdrc.io/resource/I0700
      total_pages: 692
      volume_number: 9
      volume_pages_bdrc_intro: 2
    order: 9
    base_file: I0700.txt
    statistics:
      ocr_word_median_confidence_index: 0.550000011920929
      ocr_word_mean_confidence_index: 0.5497796958050599
    legacy_id: v009
  I0695:
    source_metadata:
      id: http://purl.bdrc.io/resource/I0695
      total_pages: 688
      volume_number: 4
      volume_pages_bdrc_intro: 2
    order: 4
    base_file: I0695.txt
    statistics:
      ocr_word_median_confidence_index: 0.6200000047683716
      ocr_word_mean_confidence_index: 0.5957450318647457
    legacy_id: v004
  I0696:
    source_metadata:
      id: http://purl.bdrc.io/resource/I0696
      total_pages: 716
      volume_number: 5
      volume_pages_bdrc_intro: 2
    order: 5
    base_file: I0696.txt
    statistics:
      ocr_word_median_confidence_index: 0.6200000047683716
      ocr_word_mean_confidence_index: 0.6015455519696269
    legacy_id: v005
  I0702:
    source_metadata:
      id: http://purl.bdrc.io/resource/I0702
      total_pages: 776
      volume_number: 11
      volume_pages_bdrc_intro: 2
    order: 11
    base_file: I0702.txt
    statistics:
      ocr_word_median_confidence_index: 0.5199999809265137
      ocr_word_mean_confidence_index: 0.5359009225375849
    legacy_id: v011
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
