id: P007004
initial_creation_type: ocr
source_metadata:
  id: bdr:W23693
  title: གསུང་འབུམ། མཁས་གྲུབ་རྗེ ༼སྐུ་འབུམ་པར་མ༽
  author: ''
  volumes:
    8764feab32fc40b18acca04be74d6598:
      image_group_id: I0692
      title: ''
      volume_number: 1
      total_pages: 810
      base_file: v001.txt
    e47fbf1c048e44e3afdb86bac45b481e:
      image_group_id: I0693
      title: ''
      volume_number: 2
      total_pages: 826
      base_file: v002.txt
    efbd5b678162466685ca7dd940e03a17:
      image_group_id: I0694
      title: ''
      volume_number: 3
      total_pages: 700
      base_file: v003.txt
    963d631d029d4c8282f4dcfcbff5af9f:
      image_group_id: I0695
      title: ''
      volume_number: 4
      total_pages: 688
      base_file: v004.txt
    3789e631b06d4ecebe77e76e709dcac1:
      image_group_id: I0696
      title: ''
      volume_number: 5
      total_pages: 716
      base_file: v005.txt
    bae820395ac54117939610adc5c4379e:
      image_group_id: I0697
      title: ''
      volume_number: 6
      total_pages: 754
      base_file: v006.txt
    d276de059ea243c9a71ed4ae9e5f6f9b:
      image_group_id: I0698
      title: ''
      volume_number: 7
      total_pages: 810
      base_file: v007.txt
    8b0efce025144a43875b8f1d762e5f3d:
      image_group_id: I0699
      title: ''
      volume_number: 8
      total_pages: 812
      base_file: v008.txt
    d5d8d1a636bc430493cca0c5b79bac06:
      image_group_id: I0700
      title: ''
      volume_number: 9
      total_pages: 692
      base_file: v009.txt
    d6a4871bfbdb4e84a196f405db849e9e:
      image_group_id: I0701
      title: ''
      volume_number: 10
      total_pages: 832
      base_file: v010.txt
    90b07ec580bc4d2e9aa625c32cde0f07:
      image_group_id: I0702
      title: ''
      volume_number: 11
      total_pages: 776
      base_file: v011.txt
    0a4ff4c81d0d43ecadb0d814b12b77ab:
      image_group_id: I0703
      title: ''
      volume_number: 12
      total_pages: 696
      base_file: v012.txt
    7bdc67c5f07f405581362ac9f3ebd1e5:
      image_group_id: I0704
      title: ''
      volume_number: 13
      total_pages: 800
      base_file: v013.txt
    48b8c7536df54b5a8fc8d79a08b11816:
      image_group_id: I0705
      title: ''
      volume_number: 14
      total_pages: 766
      base_file: v014.txt
    f1e15c0781be449baf8aea55038e81af:
      image_group_id: I0706
      title: ''
      volume_number: 15
      total_pages: 790
      base_file: v015.txt
    d17741610cbb4e8f8c08eea6e89316eb:
      image_group_id: I0707
      title: ''
      volume_number: 16
      total_pages: 712
      base_file: v016.txt
ebook_metadata:
  title: གསུང་འབུམ། མཁས་གྲུབ་རྗེ ༼སྐུ་འབུམ་པར་མ༽
  author: ''
  sku: P007004
  cover: cover.jpg
  layers:
  - pagination
